jobs:
  review-dependabot-pr:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' && github.repository
      == 'tls-attacker/TLS-Attacker-Development' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: dependabot-metadata
      name: Dependabot metadata
      uses: dependabot/fetch-metadata@v1
    - continue-on-error: true
      id: generate-token
      name: Generate temporary access token for GitHub app
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.DEPENDABOT_REVIEWER_APP_ID }}
        private_key: ${{ secrets.DEPENDABOT_REVIEWER_PRIVATE_KEY }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        PR_URL: ${{github.event.pull_request.html_url}}
      name: Enable auto-merge for Dependabot PRs
      run: gh pr merge --auto --merge "$PR_URL"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        PR_URL: ${{github.event.pull_request.html_url}}
      if: ${{ steps.dependabot-metadata.outputs.dependency-names == 'de.rub.nds:protocol-toolkit-bom'
        }}
      name: Approve any update of protocol-toolkit-bom
      run: gh pr review $PR_URL --approve -b "I'm **approving** this pull request
        because **it is a BOM update**"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        PR_URL: ${{github.event.pull_request.html_url}}
      if: ${{ (steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
        || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor')
        && steps.dependabot-metadata.outputs.dependency-names != 'de.rub.nds:protocol-toolkit-bom'
        }}
      name: Approve patch and minor updates of other dependencies
      run: gh pr review $PR_URL --approve -b "I'm **approving** this pull request
        because **it includes a patch or minor update**"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        PR_URL: ${{github.event.pull_request.html_url}}
      if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major'
        && steps.dependabot-metadata.outputs.dependency-type == 'direct:development'
        }}
      name: Approve major updates of development dependencies
      run: gh pr review $PR_URL --approve -b "I'm **approving** this pull request
        because **it includes a major update of a dependency used only in development**"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        PR_URL: ${{github.event.pull_request.html_url}}
      if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major'
        && steps.dependabot-metadata.outputs.dependency-type == 'direct:production'
        && steps.dependabot-metadata.outputs.dependency-names != 'de.rub.nds:protocol-toolkit-bom'
        }}
      name: Comment on major updates of non-development dependencies and request review
        from tls-attacker-extended
      run: 'gh pr comment $PR_URL --body "I''m **not approving** this PR because **it
        includes a major update of a dependency used in production**"

        gh pr edit $PR_URL --add-label "help wanted" --add-reviewer "tls-attacker/tls-attacker-extended"

        '
name: dependabot Reviewer
on:
  repository_dispatch:
    types: trigger-ga___dependabot-reviewer.yml
permissions:
  contents: read
  pull-requests: read
