jobs:
  test:
    if: github.repository == 'tls-attacker/TLS-Attacker'
    name: Test TLS-Attacker on JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }} ${{ matrix.os }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test
      run: mvn clean test
    - continue-on-error: true
      name: package
      run: mvn clean package
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
      max-parallel: 4
name: TLS-Attacker
on:
  repository_dispatch:
    types: trigger-ga___main.yml
